APPLICATION = iot2023joonajanne

BOARD ?= iotlab-m3

USEMODULE += ztimer_msec
USEMODULE += lps331ap
USEMODULE += isl29020

FEATURES_REQUIRED += periph_uart

RIOTBASE ?= $(CURDIR)/../../include/RIOT

include $(RIOTBASE)/Makefile.include
